# Generated by Django 2.2.5 on 2020-01-13 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('rating1', models.PositiveIntegerField()),
                ('rating2', models.PositiveIntegerField()),
                ('rating3', models.PositiveIntegerField()),
                ('rating4', models.PositiveIntegerField()),
                ('rating5', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Libro')),
            ],
        ),
    ]
