# Generated by Django 2.0.13 on 2019-12-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191128_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('eventoId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(help_text='Nombre del evento', verbose_name='Evento')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio ', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización', verbose_name='Fecha de Finalización ')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio', max_digits=5, verbose_name='Precio')),
            ],
            options={
                'ordering': ('fecha_inicio',),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idiomaId', models.TextField(primary_key=True, serialize=False)),
                ('idioma', models.TextField(help_text='Idioma', verbose_name='Idioma')),
            ],
            options={
                'ordering': ('idioma',),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipioId', models.TextField(primary_key=True, serialize=False)),
                ('municipio', models.TextField(help_text='Municipio', verbose_name='Municipio')),
            ],
            options={
                'ordering': ('municipio',),
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.TextField(help_text='Tipo de evento', verbose_name='Tipo de Evento')),
            ],
            options={
                'ordering': ('tipo_evento',),
            },
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuaciones',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idPelicula',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ocupacion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='idiomas',
            field=models.ManyToManyField(to='main.Idioma'),
        ),
        migrations.AddField(
            model_name='evento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Municipio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoEvento'),
        ),
    ]
